CREATE DATABASE joelScan IF NOT EXISTS;

USE joelScan;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    creationDAte DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS joels (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    count DOUBLE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS connectionTokens (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    token VARCHAR(100) NOT NULL,
    availableTime VARCHAR(10) NOT NULL,
    creationTime DATETIME NOT NULL
);